


#==============================================================================
# Web Server configuration
#==============================================================================
indexFile: index.html
port: 8081

#==============================================================================
# SSL configuration
#==============================================================================
useSSL: false
keyStorePassword: test


