


#==============================================================================
# Web Server configuration
#==============================================================================
webserver:
  indexFile: index.html
  port: 8081
ssl:
  useSSL: false
  keyStorePassword: test
api:
  whitelistPlaceholders: false
  placeholder-whitelist:
    - 'server_online'
    - 'server_max_players'
