


#==============================================================================
# Web Server configuration
#==============================================================================
webserver:
  domain: localhost
  indexFile: index.html
  port: 8081
ssl:
  useSSL: false
  keystorePassword: test
api:
  apiOnly: false
  whitelistPlaceholders: false
  placeholder-whitelist:
    - 'server_online'
    - 'server_max_players'
